services:
  - type: web
    name: ems-project
    runtime: python
    buildCommand: "pip install -r requirements.txt && DJANGO_SETTINGS_MODULE=ems_project.ems_project.settings python ems_project/manage.py collectstatic --noinput"
    startCommand: "DJANGO_SETTINGS_MODULE=ems_project.ems_project.settings python ems_project/manage.py migrate --noinput && gunicorn ems_project.ems_project.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: ems_project.ems_project.settings
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: "employee-management-system-ukpf.onrender.com,.onrender.com"
      - key: DEBUG
        value: "False"
