services:
  - type: web
    name: ems-project
    runtime: python
    buildCommand: "pip install -r requirements.txt && cd ems_project && python manage.py collectstatic --noinput && python manage.py migrate"
    startCommand: "gunicorn ems_project.wsgi:application --chdir ems_project"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: ems_project.settings
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: DEBUG
        value: "False"
